// Auto-generated by .agent/skills/fonts/scripts/sync-fonts.js

export const FONT_FILES: Record<string, Record<string, string[]>> = {
  "Comic Mono": {
    "400": [
      "/fonts/comic-mono-latin-400-normal.woff"
    ],
    "700": [
      "/fonts/comic-mono-latin-700-normal.woff"
    ],
    "normal": [
      "/fonts/comic-mono-latin-400-normal.woff"
    ],
    "bold": [
      "/fonts/comic-mono-latin-700-normal.woff"
    ]
  },
  "Comic Neue": {
    "300": [
      "/fonts/comic-neue-latin-300-normal.woff"
    ],
    "400": [
      "/fonts/comic-neue-latin-400-normal.woff"
    ],
    "700": [
      "/fonts/comic-neue-latin-700-normal.woff"
    ],
    "normal": [
      "/fonts/comic-neue-latin-400-normal.woff"
    ],
    "bold": [
      "/fonts/comic-neue-latin-700-normal.woff"
    ]
  },
  "Geist Sans": {
    "100": [
      "/fonts/geist-sans-latin-100-normal.woff"
    ],
    "200": [
      "/fonts/geist-sans-latin-200-normal.woff"
    ],
    "300": [
      "/fonts/geist-sans-latin-300-normal.woff"
    ],
    "400": [
      "/fonts/geist-sans-latin-400-normal.woff"
    ],
    "500": [
      "/fonts/geist-sans-latin-500-normal.woff"
    ],
    "600": [
      "/fonts/geist-sans-latin-600-normal.woff"
    ],
    "700": [
      "/fonts/geist-sans-latin-700-normal.woff"
    ],
    "800": [
      "/fonts/geist-sans-latin-800-normal.woff"
    ],
    "900": [
      "/fonts/geist-sans-latin-900-normal.woff"
    ],
    "normal": [
      "/fonts/geist-sans-latin-400-normal.woff"
    ],
    "bold": [
      "/fonts/geist-sans-latin-700-normal.woff"
    ]
  },
  "Inter": {
    "100": [
      "/fonts/inter-latin-100-normal.woff",
      "/fonts/inter-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/inter-latin-200-normal.woff",
      "/fonts/inter-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/inter-latin-300-normal.woff",
      "/fonts/inter-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/inter-latin-400-normal.woff",
      "/fonts/inter-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/inter-latin-500-normal.woff",
      "/fonts/inter-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/inter-latin-600-normal.woff",
      "/fonts/inter-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/inter-latin-700-normal.woff",
      "/fonts/inter-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/inter-latin-800-normal.woff",
      "/fonts/inter-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/inter-latin-900-normal.woff",
      "/fonts/inter-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/inter-latin-400-normal.woff",
      "/fonts/inter-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/inter-latin-700-normal.woff",
      "/fonts/inter-latin-ext-700-normal.woff"
    ]
  },
  "Lato": {
    "100": [
      "/fonts/lato-latin-100-normal.woff",
      "/fonts/lato-latin-ext-100-normal.woff"
    ],
    "300": [
      "/fonts/lato-latin-300-normal.woff",
      "/fonts/lato-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/lato-latin-400-normal.woff",
      "/fonts/lato-latin-ext-400-normal.woff"
    ],
    "700": [
      "/fonts/lato-latin-700-normal.woff",
      "/fonts/lato-latin-ext-700-normal.woff"
    ],
    "900": [
      "/fonts/lato-latin-900-normal.woff",
      "/fonts/lato-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/lato-latin-400-normal.woff",
      "/fonts/lato-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/lato-latin-700-normal.woff",
      "/fonts/lato-latin-ext-700-normal.woff"
    ]
  },
  "Montserrat": {
    "100": [
      "/fonts/montserrat-latin-100-normal.woff",
      "/fonts/montserrat-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/montserrat-latin-200-normal.woff",
      "/fonts/montserrat-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/montserrat-latin-300-normal.woff",
      "/fonts/montserrat-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/montserrat-latin-400-normal.woff",
      "/fonts/montserrat-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/montserrat-latin-500-normal.woff",
      "/fonts/montserrat-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/montserrat-latin-600-normal.woff",
      "/fonts/montserrat-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/montserrat-latin-700-normal.woff",
      "/fonts/montserrat-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/montserrat-latin-800-normal.woff",
      "/fonts/montserrat-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/montserrat-latin-900-normal.woff",
      "/fonts/montserrat-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/montserrat-latin-400-normal.woff",
      "/fonts/montserrat-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/montserrat-latin-700-normal.woff",
      "/fonts/montserrat-latin-ext-700-normal.woff"
    ]
  },
  "Noto Sans": {
    "100": [
      "/fonts/noto-sans-latin-100-normal.woff",
      "/fonts/noto-sans-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/noto-sans-latin-200-normal.woff",
      "/fonts/noto-sans-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/noto-sans-latin-300-normal.woff",
      "/fonts/noto-sans-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/noto-sans-latin-400-normal.woff",
      "/fonts/noto-sans-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/noto-sans-latin-500-normal.woff",
      "/fonts/noto-sans-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/noto-sans-latin-600-normal.woff",
      "/fonts/noto-sans-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/noto-sans-latin-700-normal.woff",
      "/fonts/noto-sans-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/noto-sans-latin-800-normal.woff",
      "/fonts/noto-sans-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/noto-sans-latin-900-normal.woff",
      "/fonts/noto-sans-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/noto-sans-latin-400-normal.woff",
      "/fonts/noto-sans-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/noto-sans-latin-700-normal.woff",
      "/fonts/noto-sans-latin-ext-700-normal.woff"
    ]
  },
  "Nunito": {
    "200": [
      "/fonts/nunito-latin-200-normal.woff",
      "/fonts/nunito-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/nunito-latin-300-normal.woff",
      "/fonts/nunito-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/nunito-latin-400-normal.woff",
      "/fonts/nunito-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/nunito-latin-500-normal.woff",
      "/fonts/nunito-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/nunito-latin-600-normal.woff",
      "/fonts/nunito-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/nunito-latin-700-normal.woff",
      "/fonts/nunito-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/nunito-latin-800-normal.woff",
      "/fonts/nunito-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/nunito-latin-900-normal.woff",
      "/fonts/nunito-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/nunito-latin-400-normal.woff",
      "/fonts/nunito-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/nunito-latin-700-normal.woff",
      "/fonts/nunito-latin-ext-700-normal.woff"
    ]
  },
  "Nunito Sans": {
    "200": [
      "/fonts/nunito-sans-latin-200-normal.woff",
      "/fonts/nunito-sans-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/nunito-sans-latin-300-normal.woff",
      "/fonts/nunito-sans-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/nunito-sans-latin-400-normal.woff",
      "/fonts/nunito-sans-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/nunito-sans-latin-500-normal.woff",
      "/fonts/nunito-sans-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/nunito-sans-latin-600-normal.woff",
      "/fonts/nunito-sans-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/nunito-sans-latin-700-normal.woff",
      "/fonts/nunito-sans-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/nunito-sans-latin-800-normal.woff",
      "/fonts/nunito-sans-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/nunito-sans-latin-900-normal.woff",
      "/fonts/nunito-sans-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/nunito-sans-latin-400-normal.woff",
      "/fonts/nunito-sans-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/nunito-sans-latin-700-normal.woff",
      "/fonts/nunito-sans-latin-ext-700-normal.woff"
    ]
  },
  "Oswald": {
    "200": [
      "/fonts/oswald-latin-200-normal.woff",
      "/fonts/oswald-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/oswald-latin-300-normal.woff",
      "/fonts/oswald-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/oswald-latin-400-normal.woff",
      "/fonts/oswald-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/oswald-latin-500-normal.woff",
      "/fonts/oswald-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/oswald-latin-600-normal.woff",
      "/fonts/oswald-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/oswald-latin-700-normal.woff",
      "/fonts/oswald-latin-ext-700-normal.woff"
    ],
    "normal": [
      "/fonts/oswald-latin-400-normal.woff",
      "/fonts/oswald-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/oswald-latin-700-normal.woff",
      "/fonts/oswald-latin-ext-700-normal.woff"
    ]
  },
  "Raleway": {
    "100": [
      "/fonts/raleway-latin-100-normal.woff",
      "/fonts/raleway-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/raleway-latin-200-normal.woff",
      "/fonts/raleway-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/raleway-latin-300-normal.woff",
      "/fonts/raleway-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/raleway-latin-400-normal.woff",
      "/fonts/raleway-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/raleway-latin-500-normal.woff",
      "/fonts/raleway-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/raleway-latin-600-normal.woff",
      "/fonts/raleway-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/raleway-latin-700-normal.woff",
      "/fonts/raleway-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/raleway-latin-800-normal.woff",
      "/fonts/raleway-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/raleway-latin-900-normal.woff",
      "/fonts/raleway-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/raleway-latin-400-normal.woff",
      "/fonts/raleway-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/raleway-latin-700-normal.woff",
      "/fonts/raleway-latin-ext-700-normal.woff"
    ]
  },
  "Roboto": {
    "100": [
      "/fonts/roboto-latin-100-normal.woff",
      "/fonts/roboto-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/roboto-latin-200-normal.woff",
      "/fonts/roboto-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/roboto-latin-300-normal.woff",
      "/fonts/roboto-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/roboto-latin-400-normal.woff",
      "/fonts/roboto-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/roboto-latin-500-normal.woff",
      "/fonts/roboto-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/roboto-latin-600-normal.woff",
      "/fonts/roboto-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/roboto-latin-700-normal.woff",
      "/fonts/roboto-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/roboto-latin-800-normal.woff",
      "/fonts/roboto-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/roboto-latin-900-normal.woff",
      "/fonts/roboto-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/roboto-latin-400-normal.woff",
      "/fonts/roboto-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/roboto-latin-700-normal.woff",
      "/fonts/roboto-latin-ext-700-normal.woff"
    ]
  },
  "Roboto Mono": {
    "100": [
      "/fonts/roboto-mono-latin-100-normal.woff",
      "/fonts/roboto-mono-latin-ext-100-normal.woff"
    ],
    "200": [
      "/fonts/roboto-mono-latin-200-normal.woff",
      "/fonts/roboto-mono-latin-ext-200-normal.woff"
    ],
    "300": [
      "/fonts/roboto-mono-latin-300-normal.woff",
      "/fonts/roboto-mono-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/roboto-mono-latin-400-normal.woff",
      "/fonts/roboto-mono-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/roboto-mono-latin-500-normal.woff",
      "/fonts/roboto-mono-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/roboto-mono-latin-600-normal.woff",
      "/fonts/roboto-mono-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/roboto-mono-latin-700-normal.woff",
      "/fonts/roboto-mono-latin-ext-700-normal.woff"
    ],
    "normal": [
      "/fonts/roboto-mono-latin-400-normal.woff",
      "/fonts/roboto-mono-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/roboto-mono-latin-700-normal.woff",
      "/fonts/roboto-mono-latin-ext-700-normal.woff"
    ]
  },
  "Rubik": {
    "300": [
      "/fonts/rubik-latin-300-normal.woff",
      "/fonts/rubik-latin-ext-300-normal.woff"
    ],
    "400": [
      "/fonts/rubik-latin-400-normal.woff",
      "/fonts/rubik-latin-ext-400-normal.woff"
    ],
    "500": [
      "/fonts/rubik-latin-500-normal.woff",
      "/fonts/rubik-latin-ext-500-normal.woff"
    ],
    "600": [
      "/fonts/rubik-latin-600-normal.woff",
      "/fonts/rubik-latin-ext-600-normal.woff"
    ],
    "700": [
      "/fonts/rubik-latin-700-normal.woff",
      "/fonts/rubik-latin-ext-700-normal.woff"
    ],
    "800": [
      "/fonts/rubik-latin-800-normal.woff",
      "/fonts/rubik-latin-ext-800-normal.woff"
    ],
    "900": [
      "/fonts/rubik-latin-900-normal.woff",
      "/fonts/rubik-latin-ext-900-normal.woff"
    ],
    "normal": [
      "/fonts/rubik-latin-400-normal.woff",
      "/fonts/rubik-latin-ext-400-normal.woff"
    ],
    "bold": [
      "/fonts/rubik-latin-700-normal.woff",
      "/fonts/rubik-latin-ext-700-normal.woff"
    ]
  }
};
