const fs = require("node:fs");
const path = require("node:path");

const ROOT_DIR = path.resolve(__dirname, "../../../..");
const PACKAGE_JSON_PATH = path.join(ROOT_DIR, "package.json");
const NODE_MODULES_DIR = path.join(ROOT_DIR, "node_modules");
const PUBLIC_FONTS_DIR = path.join(ROOT_DIR, "public", "fonts");
const FONTS_CSS_PATH = path.join(ROOT_DIR, "src", "fonts.css");
const FONTS_TS_PATH = path.join(ROOT_DIR, "src", "lib", "fonts.ts");

async function main() {
  console.log("Starting font synchronization...");

  if (!fs.existsSync(PACKAGE_JSON_PATH)) {
    console.error("package.json not found!");
    process.exit(1);
  }

  const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON_PATH, "utf-8"));
  const dependencies = { ...packageJson.dependencies, ...packageJson.devDependencies };

  const fontPackages = Object.keys(dependencies).filter((dep) => dep.startsWith("@fontsource/"));

  console.log(`Found ${fontPackages.length} font packages:`, fontPackages);

  if (!fs.existsSync(PUBLIC_FONTS_DIR)) {
    fs.mkdirSync(PUBLIC_FONTS_DIR, { recursive: true });
  }

  const fontFilesMap = {}; // fontName -> { weight -> [files] }
  const cssImports = [];

  for (const pkg of fontPackages) {
    const fontName = pkg.replace("@fontsource/", "");
    const pkgDir = path.join(NODE_MODULES_DIR, pkg);
    const filesDir = path.join(pkgDir, "files");

    if (!fs.existsSync(filesDir)) {
      console.warn(`Files directory not found for ${pkg}, skipping.`);
      continue;
    }

    const files = fs.readdirSync(filesDir).filter((file) => {
      // Include latin and latin-ext, exclude italic
      return file.endsWith(".woff") && file.includes("latin") && !file.includes("italic");
    });

    if (files.length === 0) {
      console.warn(`No suitable files found for ${pkg}.`);
      continue;
    }

    console.log(`Processing ${fontName}: found ${files.length} files.`);

    const titleCaseName = fontName
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");

    if (!fontFilesMap[titleCaseName]) {
      fontFilesMap[titleCaseName] = {};
    }

    // Sort files to ensure deterministic order
    files.sort();

    for (const file of files) {
      const sourcePath = path.join(filesDir, file);
      const destPath = path.join(PUBLIC_FONTS_DIR, file);
      fs.copyFileSync(sourcePath, destPath);

      const parts = file.split("-");
      let weight = "400";

      const latinIndex = parts.indexOf("latin");
      if (latinIndex !== -1 && parts.length > latinIndex + 1) {
        let weightIndex = latinIndex + 1;
        if (parts[weightIndex] === "ext") {
          weightIndex++;
        }
        if (parts.length > weightIndex) {
          weight = parts[weightIndex];
        }
      }

      if (!fontFilesMap[titleCaseName][weight]) {
        fontFilesMap[titleCaseName][weight] = [];
      }
      fontFilesMap[titleCaseName][weight].push(`/fonts/${file}`);

      // Add 'normal' and 'bold' aliases
      if (weight === "400") {
        // Fixed syntax here: using string indexing
        if (!fontFilesMap[titleCaseName].normal) {
          fontFilesMap[titleCaseName].normal = [];
        }
        if (!fontFilesMap[titleCaseName].normal.includes(`/fonts/${file}`)) {
          fontFilesMap[titleCaseName].normal.push(`/fonts/${file}`);
        }
      }
      if (weight === "700") {
        if (!fontFilesMap[titleCaseName].bold) {
          fontFilesMap[titleCaseName].bold = [];
        }
        if (!fontFilesMap[titleCaseName].bold.includes(`/fonts/${file}`)) {
          fontFilesMap[titleCaseName].bold.push(`/fonts/${file}`);
        }
      }

      // Add CSS import for this weight if it exists in pkg root
      const cssFile = `${weight}.css`;
      if (fs.existsSync(path.join(pkgDir, cssFile))) {
        const importStr = `@import "${pkg}/${cssFile}";`;
        if (!cssImports.includes(importStr)) {
          cssImports.push(importStr);
        }
      }
    }
  }

  // Generate src/fonts.css
  const cssContent = `/* Auto-generated by .agent/skills/fonts/scripts/sync-fonts.js */
${[...new Set(cssImports)].sort().join("\n")}
`;
  fs.writeFileSync(FONTS_CSS_PATH, cssContent);
  console.log(`Generated ${FONTS_CSS_PATH}`);

  // Generate src/lib/fonts.ts
  const tsContent = `// Auto-generated by .agent/skills/fonts/scripts/sync-fonts.js

export const FONT_FILES: Record<string, Record<string, string[]>> = ${JSON.stringify(fontFilesMap, null, 2)};
`;
  fs.writeFileSync(FONTS_TS_PATH, tsContent);
  console.log(`Generated ${FONTS_TS_PATH}`);

  console.log("Font synchronization complete.");
}

main().catch(console.error);
